extends: '../.eslintrc.yml'
#Only frontend-specific stuff should go here. Inherit the rest from root.

rules:
  react/jsx-curly-spacing:
    - error
    - never
  react/jsx-equals-spacing:
    - error
    - never
