extends: '../.eslintrc.yml'
#Only frontend-specific stuff should go here. Inherit the rest from root.
globals:
  customisation: true
env:
  browser: true
rules:
  react/jsx-curly-spacing:
    - error
    - never
  react/jsx-equals-spacing:
    - error
    - never
  import/no-named-as-default:
    - off

# TODO: Remove all proptypes
  react/forbid-prop-types:
    - warn
# TODO: Switch everything to .js (and remove references to .jsx from configs once that's done)
  react/jsx-filename-extension:
    - warn
# TODO: These are genuine a11y issues we should fix
  jsx-a11y/anchor-has-content:
    - warn
  jsx-a11y/no-static-element-interactions:
    - warn
# TODO: This is actually exposing a couple of bugs to do with closing modals. They need to be fixed
  react/no-unused-prop-types:
    - warn
# TODO: This is fixed by merging selectors into reducers (if possible)
  import/prefer-default-export:
    - warn
