extends: '../.eslintrc.yml'
#Only frontend-specific stuff should go here. Inherit the rest from root.
globals:
  customisation: true
rules:
  react/jsx-curly-spacing:
    - error
    - never
  react/jsx-equals-spacing:
    - error
    - never
  import/no-named-as-default:
    - off

#New errors brought in by eslint upgrade - to be reviewed:
  no-undef:
    - warn
  react/forbid-prop-types:
    - warn
  react/jsx-filename-extension:
    - warn
  jsx-a11y/anchor-has-content:
    - warn
  react/no-unused-prop-types:
    - warn
  jsx-a11y/no-static-element-interactions:
    - warn


  import/prefer-default-export:
    # TODO: This is fixed by merging selectors into reducers
    - warn
