extends: 'airbnb'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
rules:
  max-len:
    - error
    - 120
  new-cap:
    - error
    - capIsNewExceptions:
      - Q
  arrow-parens:
    - error
    - as-needed
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
