extends: 'airbnb'
rules:
  max-len:
    - error
    - 120
  new-cap:
    - error
    - capIsNewExceptions:
      - Q
  arrow-parens:
    - error
    - as-needed
  react/jsx-curly-spacing:
    - error
    - never
  react/jsx-equals-spacing:
    - error
    - never
