sudo: required

language: node_js
node_js:
  - "6"

services:
  - docker

install: npm install

script: ./go.sh npm test

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then bin/docker-build-and-deploy.sh; fi
