version: '3'
services:
  core:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
    ports:
      - "3000:3000"
    depends_on:
      - db
      - kinesis
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://rabble_rouser_user:rabble_rouser_password@db:5432/rabble_rouser_db
      KINESIS_ENDPOINT: http://kinesis:4567
      LISTENER_AUTH_TOKEN: secret
    command: sleep 2147483647 # Sleep forever, we'll shell into the container later
    stdin_open: true
    tty: true
  db:
    image: postgres
    environment:
      POSTGRES_USER: rabble_rouser_user
      POSTGRES_PASSWORD: rabble_rouser_password
      POSTGRES_DB: rabble_rouser_db
  event-forwarder:
    image: rabblerouser/event-forwarder
    depends_on:
      - kinesis
      - core
    environment:
      KINESIS_ENDPOINT: http://kinesis:4567
      LISTENER_ENDPOINT: http://core:3000/events
      LISTENER_AUTH_TOKEN: secret
  kinesis:
    image: instructure/kinesalite
