version: '2'
services:
  core:
    build:
      context: docker/
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
    ports:
      - "3000:3000"
      - "8080:8080"
    depends_on:
      - db
      - kinesis
      - s3
    links:
      - "s3:rr-event-archive.s3"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://rabble_rouser_user:rabble_rouser_password@db:5432/rabble_rouser_db
      TEST_DATABASE_URL: postgres://rabble_rouser_user:rabble_rouser_password@test_db:5432/rabble_rouser_db
      KINESIS_ENDPOINT: http://kinesis:4567
      S3_ENDPOINT: http://s3:4569
      LISTENER_AUTH_TOKEN: secret
      ARCHIVE_BUCKET: rr-event-archive
      STREAM_NAME: rabblerouser_stream
      TEST_STREAM_NAME: test_rabblerouser_stream
    command: sleep 2147483647 # Sleep forever, we'll shell into the container later
    stdin_open: true
    tty: true
  db:
    image: postgres
    environment:
      POSTGRES_USER: rabble_rouser_user
      POSTGRES_PASSWORD: rabble_rouser_password
      POSTGRES_DB: rabble_rouser_db
  test_db:
    image: postgres
    environment:
      POSTGRES_USER: rabble_rouser_user
      POSTGRES_PASSWORD: rabble_rouser_password
      POSTGRES_DB: rabble_rouser_db
  event-forwarder:
    image: rabblerouser/event-forwarder
    depends_on:
      - kinesis
      - core
    environment:
      KINESIS_ENDPOINT: http://kinesis:4567
      LISTENER_ENDPOINT: http://core:3000/events
      LISTENER_AUTH_TOKEN: secret
      STREAM_NAME: rabblerouser_stream
  event-archiver:
    image: rabblerouser/event-archiver
    depends_on:
      - kinesis
      - s3
    links:
      - "s3:rr-event-archive.s3"
    environment:
      KINESIS_ENDPOINT: http://kinesis:4567
      S3_ENDPOINT: http://s3:4569
      STREAM_NAME: rabblerouser_stream
      ARCHIVE_BUCKET: rr-event-archive
  kinesis:
    image: instructure/kinesalite
  s3:
    image: lphoward/fake-s3
