- name: install postgres
  apt: name=postgresql-9.3

- name: install psycopg2
  apt: name=python-psycopg2

- name: setup postgres for vagrant user
  sudo_user: postgres
  postgresql_user: name=vagrant role_attr_flags=SUPERUSER

- name: setup postgres db
  sudo_user: postgres
  postgresql_db: name=project-m

- name: setup postgres
  sudo_user: postgres
  postgresql_user: db=project-m name=project-m role_attr_flags=NOSUPERUSER,CREATEDB,LOGIN password=project-m priv=ALL

- name: setup postgres db
  sudo_user: postgres
  postgresql_db: name=project-m_test

- name: setup postgres
  sudo_user: postgres
  postgresql_user: db=project-m_test name=project-m priv=ALL

